### ISSUE TITLE
[Bug]: API calls triggering twice

### ISSUE THREAD

**Issue by RasoolMohamed27** [uwaisalqadri/MangaKu#2]
### Contact Details

rmsoftwaredeveloper@gmail.com

### What happened?

I checked `detailUseCase.getDetailManga(mangaId)` from `DetailViewModel` in **mangaku-android** , the API call is triggered twice and also the same issue happening in other API's too. Please assist on it.

### Version

1.0

### What android version are you seeing the problem on?

Android 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by uwaisalqadri** [comment]
Hi Rasool, I really appreciate this issue, my theory is that the API call happened to trigger twice because of the recomposition, basically it followed the composable function lifecycle.

It should be fixed by now https://github.com/uwaisalqadri/MangaKu/commit/8f10c652ac3d5942d648802d129f4f5b0bbe4ba3

**Comment by RasoolMohamed27** [comment]
Thank you so much for your quick fix!

I really prefer to follow your app structure for my first KMP project.
